/** This file is autogenerated using [AstGenerator.defineAst]. */
interface StatementVisitor<T> {
	fun visit(statement: Statement): T
}

sealed class Statement {
	fun <T> accept(visitor: StatementVisitor<T>): T = visitor.visit(this)

	data class Block(val statements: List<Statement>): Statement()
	data class Expr(val expr: Expression): Statement()
	data class Print(val expr: Expression): Statement()
	data class Variable(val name: Token, val value: Expression?): Statement()
}
